"""add word_type to vocabulary_cards

Revision ID: 1da20884d6da
Revises: a1b2c3d4e5f6
Create Date: 2025-12-10 14:28:02.857767

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1da20884d6da"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_user_card_favorite", "favorites", ["user_id", "card_id"])
    op.create_unique_constraint("uq_user_card", "user_card_progress", ["user_id", "card_id"])
    op.create_unique_constraint("uq_user_deck", "user_selected_decks", ["user_id", "deck_id"])
    op.add_column(
        "vocabulary_cards",
        sa.Column("word_type", sa.String(length=50), nullable=True, server_default="word"),
    )
    op.create_index(
        op.f("ix_vocabulary_cards_word_type"),
        "vocabulary_cards",
        ["word_type"],
        unique=False,
    )
    # Update existing records to have default word_type
    op.execute("UPDATE vocabulary_cards SET word_type = 'word' WHERE word_type IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vocabulary_cards_word_type"), table_name="vocabulary_cards")
    op.drop_column("vocabulary_cards", "word_type")
    op.drop_constraint("uq_user_deck", "user_selected_decks", type_="unique")
    op.drop_constraint("uq_user_card", "user_card_progress", type_="unique")
    op.drop_constraint("uq_user_card_favorite", "favorites", type_="unique")
    # ### end Alembic commands ###
