"""initial clean schema

Revision ID: 3cc3b28e5a94
Revises:
Create Date: 2025-11-20 21:22:41.764492

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cc3b28e5a94"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("longest_streak", sa.Integer(), nullable=False),
        sa.Column("last_study_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_last_study_date"), "users", ["last_study_date"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "decks",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("difficulty_level", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_official", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_decks_category"), "decks", ["category"], unique=False)
    op.create_index(op.f("ix_decks_creator_id"), "decks", ["creator_id"], unique=False)
    op.create_index(op.f("ix_decks_is_public"), "decks", ["is_public"], unique=False)
    op.create_table(
        "study_sessions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=True),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("cards_studied", sa.Integer(), nullable=False),
        sa.Column("correct_answers", sa.Integer(), nullable=False),
        sa.Column("wrong_answers", sa.Integer(), nullable=False),
        sa.Column("accuracy_rate", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["decks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_study_sessions_deck_id"), "study_sessions", ["deck_id"], unique=False)
    op.create_index(
        op.f("ix_study_sessions_session_date"), "study_sessions", ["session_date"], unique=False
    )
    op.create_index(op.f("ix_study_sessions_user_id"), "study_sessions", ["user_id"], unique=False)
    op.create_table(
        "user_decks",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("last_studied_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["decks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "deck_id", name="idx_user_decks_user_deck"),
    )
    op.create_index(op.f("ix_user_decks_deck_id"), "user_decks", ["deck_id"], unique=False)
    op.create_index(op.f("ix_user_decks_user_id"), "user_decks", ["user_id"], unique=False)
    op.create_table(
        "vocabulary_cards",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("english_word", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("korean_meaning", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("part_of_speech", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("pronunciation_ipa", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("definition_en", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("difficulty_level", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("cefr_level", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("deck_id", sa.Integer(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("example_sentences", sa.JSON(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["decks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vocabulary_cards_deck_id"), "vocabulary_cards", ["deck_id"], unique=False
    )
    op.create_index(
        op.f("ix_vocabulary_cards_difficulty_level"),
        "vocabulary_cards",
        ["difficulty_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vocabulary_cards_english_word"), "vocabulary_cards", ["english_word"], unique=False
    )
    op.create_table(
        "user_card_progress",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("interval", sa.Integer(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("total_reviews", sa.Integer(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("wrong_count", sa.Integer(), nullable=False),
        sa.Column("accuracy_rate", sa.Float(), nullable=False),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("scheduled_days", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("elapsed_days", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("next_review_date", sa.DateTime(), nullable=False),
        sa.Column("last_review_date", sa.DateTime(), nullable=True),
        sa.Column(
            "card_state",
            sa.Enum("NEW", "LEARNING", "REVIEW", "RELEARNING", name="cardstate"),
            nullable=False,
        ),
        sa.Column("first_studied_at", sa.DateTime(), nullable=True),
        sa.Column("quality_history", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["vocabulary_cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "card_id", name="uq_user_card"),
    )
    op.create_index(
        op.f("ix_user_card_progress_card_id"), "user_card_progress", ["card_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_card_progress_card_state"), "user_card_progress", ["card_state"], unique=False
    )
    op.create_index(
        op.f("ix_user_card_progress_next_review_date"),
        "user_card_progress",
        ["next_review_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_card_progress_user_id"), "user_card_progress", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_card_progress_user_id"), table_name="user_card_progress")
    op.drop_index(op.f("ix_user_card_progress_next_review_date"), table_name="user_card_progress")
    op.drop_index(op.f("ix_user_card_progress_card_state"), table_name="user_card_progress")
    op.drop_index(op.f("ix_user_card_progress_card_id"), table_name="user_card_progress")
    op.drop_table("user_card_progress")
    op.drop_index(op.f("ix_vocabulary_cards_english_word"), table_name="vocabulary_cards")
    op.drop_index(op.f("ix_vocabulary_cards_difficulty_level"), table_name="vocabulary_cards")
    op.drop_index(op.f("ix_vocabulary_cards_deck_id"), table_name="vocabulary_cards")
    op.drop_table("vocabulary_cards")
    op.drop_index(op.f("ix_user_decks_user_id"), table_name="user_decks")
    op.drop_index(op.f("ix_user_decks_deck_id"), table_name="user_decks")
    op.drop_table("user_decks")
    op.drop_index(op.f("ix_study_sessions_user_id"), table_name="study_sessions")
    op.drop_index(op.f("ix_study_sessions_session_date"), table_name="study_sessions")
    op.drop_index(op.f("ix_study_sessions_deck_id"), table_name="study_sessions")
    op.drop_table("study_sessions")
    op.drop_index(op.f("ix_decks_is_public"), table_name="decks")
    op.drop_index(op.f("ix_decks_creator_id"), table_name="decks")
    op.drop_index(op.f("ix_decks_category"), table_name="decks")
    op.drop_table("decks")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_last_study_date"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
