"""add new_cards_count and review_cards_count to study_sessions

Revision ID: 5e0888ee7d18
Revises: 1da20884d6da
Create Date: 2025-12-11 01:27:22.690374

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e0888ee7d18"
down_revision: str | Sequence[str] | None = "1da20884d6da"  # First after branchpoint
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new_cards_count and review_cards_count columns to study_sessions
    op.add_column(
        "study_sessions",
        sa.Column("new_cards_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "study_sessions",
        sa.Column("review_cards_count", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove new_cards_count and review_cards_count columns from study_sessions
    op.drop_column("study_sessions", "review_cards_count")
    op.drop_column("study_sessions", "new_cards_count")
    # ### end Alembic commands ###
