"""Add all DB schema updates: user settings, deck selection, favorites, frequency rank, audio

Revision ID: eccc1f1a2c21
Revises: 3cc3b28e5a94
Create Date: 2025-11-30 15:09:05.130184

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eccc1f1a2c21"
down_revision: str | Sequence[str] | None = "3cc3b28e5a94"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_selected_decks",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["decks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "deck_id", name="uq_user_deck"),
    )
    op.create_index(
        op.f("ix_user_selected_decks_deck_id"), "user_selected_decks", ["deck_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_selected_decks_user_id"), "user_selected_decks", ["user_id"], unique=False
    )
    op.create_table(
        "favorites",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["vocabulary_cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "card_id", name="uq_user_card_favorite"),
    )
    op.create_index(op.f("ix_favorites_card_id"), "favorites", ["card_id"], unique=False)
    op.create_index(op.f("ix_favorites_user_id"), "favorites", ["user_id"], unique=False)
    op.drop_index(op.f("ix_user_decks_deck_id"), table_name="user_decks")
    op.drop_index(op.f("ix_user_decks_user_id"), table_name="user_decks")
    op.drop_table("user_decks")
    op.drop_index(op.f("ix_study_sessions_deck_id"), table_name="study_sessions")
    op.drop_index(op.f("ix_study_sessions_session_date"), table_name="study_sessions")
    op.drop_index(op.f("ix_study_sessions_user_id"), table_name="study_sessions")
    op.drop_table("study_sessions")
    op.drop_column("user_card_progress", "wrong_count")
    op.drop_column("user_card_progress", "accuracy_rate")
    op.drop_column("user_card_progress", "first_studied_at")
    op.add_column("users", sa.Column("select_all_decks", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("daily_goal", sa.Integer(), nullable=False))
    op.add_column(
        "users", sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False)
    )
    op.add_column(
        "users", sa.Column("theme", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False)
    )
    op.add_column("users", sa.Column("notification_enabled", sa.Boolean(), nullable=False))
    op.add_column(
        "vocabulary_cards",
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    )
    op.add_column("vocabulary_cards", sa.Column("frequency_rank", sa.Integer(), nullable=True))
    op.add_column(
        "vocabulary_cards",
        sa.Column("audio_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    )
    op.create_index(
        op.f("ix_vocabulary_cards_frequency_rank"),
        "vocabulary_cards",
        ["frequency_rank"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vocabulary_cards_frequency_rank"), table_name="vocabulary_cards")
    op.drop_column("vocabulary_cards", "audio_url")
    op.drop_column("vocabulary_cards", "frequency_rank")
    op.drop_column("vocabulary_cards", "category")
    op.drop_column("users", "notification_enabled")
    op.drop_column("users", "theme")
    op.drop_column("users", "timezone")
    op.drop_column("users", "daily_goal")
    op.drop_column("users", "select_all_decks")
    op.add_column(
        "user_card_progress",
        sa.Column("first_studied_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user_card_progress",
        sa.Column(
            "accuracy_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "user_card_progress",
        sa.Column("wrong_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_table(
        "study_sessions",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("deck_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("duration_minutes", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("cards_studied", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("correct_answers", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("wrong_answers", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "accuracy_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("ended_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["deck_id"], ["decks.id"], name=op.f("study_sessions_deck_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("study_sessions_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("study_sessions_pkey")),
    )
    op.create_index(op.f("ix_study_sessions_user_id"), "study_sessions", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_study_sessions_session_date"), "study_sessions", ["session_date"], unique=False
    )
    op.create_index(op.f("ix_study_sessions_deck_id"), "study_sessions", ["deck_id"], unique=False)
    op.create_table(
        "user_decks",
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("deck_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("last_studied_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"], name=op.f("user_decks_deck_id_fkey")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("user_decks_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("user_decks_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "deck_id",
            name=op.f("idx_user_decks_user_deck"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_user_decks_user_id"), "user_decks", ["user_id"], unique=False)
    op.create_index(op.f("ix_user_decks_deck_id"), "user_decks", ["deck_id"], unique=False)
    op.drop_index(op.f("ix_favorites_user_id"), table_name="favorites")
    op.drop_index(op.f("ix_favorites_card_id"), table_name="favorites")
    op.drop_table("favorites")
    op.drop_index(op.f("ix_user_selected_decks_user_id"), table_name="user_selected_decks")
    op.drop_index(op.f("ix_user_selected_decks_deck_id"), table_name="user_selected_decks")
    op.drop_table("user_selected_decks")
    # ### end Alembic commands ###
